#! /usr/bin/bash

REPO="chk50-2022s-cprog"

if [ $# -eq 0 ]
then
   cmd="check50 jy3736/$REPO/main/`basename "$PWD"` --local"
else
   cmd="echo check50 jy3736/$REPO/main/$1 --local"
fi

echo $cmd

$cmd

